USE nit;

SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 AND age < 25;

SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 OR age < 25;

UPDATE CUSTOMERS SET ADDRESS = 'Pune' WHERE ID = 6;

UPDATE CUSTOMERS SET ADDRESS = 'Pune', SALARY = 1000.00;

SELECT * FROM CUSTOMERS;

DELETE FROM CUSTOMERS WHERE ID = 6;

INSERT INTO CUSTOMERS 
VALUES (6,"Komal",22,"MP",4500.00);

SELECT * FROM CUSTOMERS WHERE SALARY LIKE '200%';

SELECT * FROM CUSTOMERS LIMIT 3;

SELECT * FROM CUSTOMERS ORDER BY NAME, SALARY;

SELECT * FROM CUSTOMERS ORDER BY NAME DESC;

SELECT NAME, SUM(SALARY) FROM CUSTOMERS GROUP BY NAME;

SELECT DISTINCT SALARY FROM CUSTOMERS ORDER BY SALARY;

SELECT * FROM CUSTOMERS 
ORDER BY (CASE ADDRESS 
WHEN 'DELHI' THEN 1 
WHEN 'BHOPAL' THEN 2 
WHEN 'KOTA' THEN 3 
WHEN 'AHMADABAD' THEN 4 
WHEN 'MP' THEN 5 
ELSE 100 END) ASC, ADDRESS DESC;

