CREATE DATABASE NIT;

USE NIT;
CREATE TABLE CUSTOMERS( ID INT NOT NULL, NAME VARCHAR (20) NOT NULL, AGE INT NOT NULL, ADDRESS CHAR (25) , SALARY DECIMAL (18, 2), PRIMARY KEY (ID) );

INSERT INTO CUSTOMERS VALUES(1, "Ramesh",32, "Ahmedabad",2000.0);
SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS 
VALUES 	(2,"Khilan",25,"Delhi",1500.00),
		(3,"kaushik",23,"Kota",2000.00),
        (4, "Chaitali",25, "Mumbai",6500.00),
        (5, "Hardik",27, "Bhopal",8500.00),
        (6,"Komal",22,"MP",4500.00),
        (7, "Muffy",24, "Indore",10000.00);
        
SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE SALARY > 5000;

SELECT * FROM CUSTOMERS WHERE SALARY = 2000;

SELECT * FROM CUSTOMERS WHERE SALARY != 2000;

SELECT * FROM CUSTOMERS WHERE SALARY >= 6500;

SELECT * FROM CUSTOMERS WHERE AGE >= 25 AND SALARY >= 6500;

SELECT * FROM CUSTOMERS WHERE AGE >= 25 OR SALARY >= 6500;

SELECT * FROM CUSTOMERS WHERE AGE IS NOT NULL;

SELECT * FROM CUSTOMERS WHERE NAME LIKE 'Ko%';

SELECT * FROM CUSTOMERS WHERE AGE IN ( 25, 27 );

SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 25 AND 27;

SELECT AGE FROM CUSTOMERS WHERE EXISTS (SELECT AGE FROM CUSTOMERS WHERE SALARY > 6500);

SELECT * FROM CUSTOMERS WHERE AGE > ALL (SELECT AGE FROM CUSTOMERS WHERE SALARY > 6500);

SELECT * FROM CUSTOMERS WHERE AGE > ANY (SELECT AGE FROM CUSTOMERS WHERE SALARY > 6500);

SELECT * FROM CUSTOMERS WHERE SALARY = 10000;

SELECT COUNT(*) AS "RECORDS" FROM CUSTOMERS;

SELECT CURRENT_TIMESTAMP;

CREATE DATABASE testDB;

SHOW DATABASES;

DROP DATABASE testDB;

USE nit;

CREATE TABLE SALARY AS SELECT ID, SALARY FROM CUSTOMERS;

DESC CUSTOMERS;

SELECT ID, NAME, SALARY FROM CUSTOMERS;



